# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  buildVersion: '1.0.0'

pool:
  vmImage: ubuntu-latest
 # creates an environment if it doesn't exist
# environment: 
#   name: 'facturacion-env'
# environment: facturacion-env
stages:
  - stage: Build
    jobs:
    
      - job: Build_Django_app 
        displayName: 'Build and zip Django app'
        steps:
          - script: |
              # Create a temporary directory to copy Django project files
              mkdir temp_django_project
              
              # Copy Django project files excluding unwanted folders
              rsync -av --exclude *.sqlite3 --exclude manage.py --exclude 'server/' --exclude */__pycache__  --exclude */Views/__pycache__ --exclude 'env39/' --exclude '.vscode/' --exclude 'migrations/' $(System.DefaultWorkingDirectory)/src/ temp_django_project/

              zip -r django-app-files.zip ./temp_django_project/*

            displayName: 'Copy Django Project Files'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: './django-app-files.zip'
              artifact: 'django-app-files'
            displayName: 'Publish Django App Files Artifact'


  - stage: Deploy
    displayName: "Deploy to the main server"
    dependsOn: Build
    condition: succeeded()
    jobs:
    - deployment: Deploy
      environment: prod-env
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: django-app-files
              - script: |
                  # Unzip the Angular build artifact
                  cd /home/vsts/work/1/django-app-files
                  unzip ./django-app-files.zip -d ./django-app-files-unzip/
                displayName: 'Unzip Django Build Artifact'
              - task: FTPUpload@2  # Use FTPUpload task
                displayName: "Upload Django app files"
                inputs:
                  credentialsOption: 'inputs'
                  serverUrl: 'ftp://ftp.huellitasvetspa.com'  # Replace with your FTP server URL
                  username: 'ftptechosur@techosur.com'  # Define FTP_USERNAME variable in Azure DevOps
                  password: 'yfItyOQXx26Y'  # Define FTP_PASSWORD variable in Azure DevOps
                  rootDirectory: '/home/vsts/work/1/django-app-files/django-app-files-unzip/temp_django_project'  # Path to your Angular build directory
                  filePatterns: '**'
                  preservePaths: true
                  remoteDirectory: '/api-datos-sunat.pacasoft.cloud'  # Destination directory on the FTP server
                  clean: false  # Clean remote directory before uploading
                  trustSSL: true
                  skipIfNotExists: true
              