# Generated by Django 4.2.9 on 2024-01-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, max_length=8)),
                ('nombres', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('ubigeo', models.CharField(blank=True, max_length=200, null=True)),
                ('provincia', models.CharField(blank=True, max_length=200, null=True)),
                ('departamento', models.CharField(blank=True, max_length=200, null=True)),
                ('distrito', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.TextField(blank=True, default='-', null=True)),
            ],
            options={
                'verbose_name_plural': 'DNIs',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='RUC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(db_index=True, max_length=11)),
                ('razon_social', models.CharField(max_length=200)),
                ('estado_contribuyente', models.CharField(max_length=200)),
                ('condicion_domicilio', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ubigeo', models.CharField(blank=True, max_length=200, null=True)),
                ('provincia', models.CharField(blank=True, max_length=200, null=True)),
                ('distrito', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_via', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_via', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_zona', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_zona', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_dir', models.CharField(blank=True, max_length=200, null=True)),
                ('interior', models.CharField(blank=True, max_length=200, null=True)),
                ('lote', models.CharField(blank=True, max_length=200, null=True)),
                ('departamento', models.CharField(blank=True, max_length=200, null=True)),
                ('manzana', models.CharField(blank=True, max_length=200, null=True)),
                ('kilometro', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'RUCs',
                'ordering': ['numero'],
            },
        ),
    ]
